Enabled model and resource class configuration.
ryangjchandler/filament-navigation pull request #53
Opened 2022-11-15 20:34 UTC by danielbehrendt

2022-11-15 20:37 UTC, ryangjchandler requested changes

2022-11-15 20:37 UTC, ryangjchandler commented on src/FilamentNavigationServiceProvider.php
> +    protected function getStyles(): array
Hm, think this should be back the way it was before...

2022-11-15 21:05 UTC, danielbehrendt commented on src/FilamentNavigationServiceProvider.php
> +    protected function getStyles(): array
Yes, you are right. Sorry, this happens accidently.

2022-11-17 17:28 UTC, ryangjchandler approved these changes

2022-11-17 17:28 UTC, merged